/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superresolution;

import java.awt.image.BufferedImage;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SelectorFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectorFrame
     */
    public SelectorFrame() {
        initComponents();
        setTitle("Selector");
        setLocation(350, 150);
        ButtonGroupUpsampling= new ButtonGroup();
        ButtonGroupUpsampling.add(jRadioButtonBilinear);
        ButtonGroupUpsampling.add(jRadioButtonBicubic);
        
        ButtonGroupEdgeSeg= new ButtonGroup();
        ButtonGroupEdgeSeg.add(jRadioButtonSobel);
        ButtonGroupEdgeSeg.add(jRadioButtonCanny);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUpsampling = new javax.swing.JLabel();
        jLabelEdgeSegmentation = new javax.swing.JLabel();
        jRadioButtonBilinear = new javax.swing.JRadioButton();
        jRadioButtonBicubic = new javax.swing.JRadioButton();
        jRadioButtonSobel = new javax.swing.JRadioButton();
        jRadioButtonCanny = new javax.swing.JRadioButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUpsampling.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelUpsampling.setText("Select the Edge Segmentation method");

        jLabelEdgeSegmentation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEdgeSegmentation.setText("Select the upsampling method");

        jRadioButtonBilinear.setText("Bilinear Method");

        jRadioButtonBicubic.setText("Bicubic Method");

        jRadioButtonSobel.setText("Sobel Operator");

        jRadioButtonCanny.setText("Canny Technique");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonCanny)
                    .addComponent(jRadioButtonSobel)
                    .addComponent(jRadioButtonBicubic)
                    .addComponent(jRadioButtonBilinear)
                    .addComponent(jLabelUpsampling, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabelEdgeSegmentation, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jRadioButtonBilinear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonBicubic)
                .addGap(18, 18, 18)
                .addComponent(jLabelUpsampling, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSobel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCanny)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabelEdgeSegmentation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
      
        BufferedImage img=null;
        if(jRadioButtonBilinear.isSelected())
        {
            String input = JOptionPane.showInputDialog("Enter The upscale factor");
            SuperResolution.upscaleFactor=Integer.parseInt(input);
            SuperResolution.PixelArray = new BiLinear().BiLine(SuperResolution.PixelArray,DemoPanel.width,DemoPanel.height,SuperResolution.upscaleFactor);
            DemoPanel.width *=SuperResolution.upscaleFactor ; DemoPanel.height *=SuperResolution.upscaleFactor;
            img=ReadWriteJPG.ConvertToImg(SuperResolution.PixelArray, DemoPanel.width, DemoPanel.height,"Bilinear.jpg");
        }
        else
        {}
        
        if(jRadioButtonSobel.isSelected())
        {
            (new EdgeSegmentFrame(SuperResolution.PixelArray,img)).setVisible(true);
        }
        else
        {}
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorFrame().setVisible(true);
            }
        });
    }
    private ButtonGroup ButtonGroupUpsampling;
    private ButtonGroup ButtonGroupEdgeSeg;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelEdgeSegmentation;
    private javax.swing.JLabel jLabelUpsampling;
    private javax.swing.JRadioButton jRadioButtonBicubic;
    private javax.swing.JRadioButton jRadioButtonBilinear;
    private javax.swing.JRadioButton jRadioButtonCanny;
    private javax.swing.JRadioButton jRadioButtonSobel;
    // End of variables declaration//GEN-END:variables
}
