/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superresolution;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import static superresolution.MedianFilter.outpixel;

/**
 *
 * @author NIT Jalandhar
 */
public class SuperResolution extends javax.swing.JFrame {

    /**
     * Creates new form SuperResolution
     */
	String fname;
	String ImageName;
	static BufferedImage InputImage;
        static int PixelArray[],EdgeArray[]; 
	DemoPanel pane;
	static int p, q, r,upscaleFactor;

    public SuperResolution() {
        setTitle("Super Resolution");
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEnhance = new javax.swing.JMenu();
        jMenuItemContrast = new javax.swing.JMenuItem();
        jMenuItemFCC = new javax.swing.JMenuItem();
        jMenuItemZoomIn = new javax.swing.JMenuItem();
        jMenuItemZoomOut = new javax.swing.JMenuItem();
        jMenuType = new javax.swing.JMenu();
        jMenuItemSingleFrame = new javax.swing.JMenuItem();
        jMenuItemMultiFrame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEnhance.setText("Enhance");

        jMenuItemContrast.setText("Contrast");
        jMenuItemContrast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContrastActionPerformed(evt);
            }
        });
        jMenuEnhance.add(jMenuItemContrast);

        jMenuItemFCC.setText("FCC");
        jMenuEnhance.add(jMenuItemFCC);

        jMenuItemZoomIn.setText("Zoom In");
        jMenuItemZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZoomInActionPerformed(evt);
            }
        });
        jMenuEnhance.add(jMenuItemZoomIn);

        jMenuItemZoomOut.setText("Zoom Out");
        jMenuItemZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZoomOutActionPerformed(evt);
            }
        });
        jMenuEnhance.add(jMenuItemZoomOut);

        jMenuBar1.add(jMenuEnhance);

        jMenuType.setText("Type");

        jMenuItemSingleFrame.setText("Single Frame");
        jMenuItemSingleFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSingleFrameActionPerformed(evt);
            }
        });
        jMenuType.add(jMenuItemSingleFrame);

        jMenuItemMultiFrame.setText("Multi Frame");
        jMenuType.add(jMenuItemMultiFrame);

        jMenuBar1.add(jMenuType);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemContrastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContrastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemContrastActionPerformed

    private void jMenuItemZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZoomInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemZoomInActionPerformed

    private void jMenuItemZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZoomOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemZoomOutActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        
			DemoPanel.count	 = 0;
			
			JFileChooser chooser = new JFileChooser();
			int r1 = chooser.showOpenDialog(this);
			if (r1 == chooser.APPROVE_OPTION)
			{
				File file = chooser.getSelectedFile();
				String name = file.getName();
                                
                                if(name.substring(name.lastIndexOf('.')+1).equalsIgnoreCase("jpg"))
                                {
                                    try {
                                        InputImage = ImageIO.read(file);
                                        jMenuEnhance.setEnabled(false);
                                        } catch (IOException ex) { }
                                }
                                
                                else
                                {   ReadBilHdrFile Rid1 = new ReadBilHdrFile(file);
                                    this.ImageName = name;
                                    ReadBil Picture1 = new ReadBil();
                                    ReadBil.setimage(name);

                                    String s;
                                    try
                                    {
                                            p = q = r = 1;
                                            InputImage = Picture1.getpicdata(p, q, r);

                                    }
                                    catch (Exception e)
                                    {
                                            System.out.println("File Open Exception : " + e);
                                    }
                                    
                                }
                                DemoPanel.setImageName(file.getPath());
                                displayImage(InputImage);     
				System.gc();
				validate();
		//		enh = 0;                              //for enhancenent
			}
        
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSingleFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSingleFrameActionPerformed
        
        PixelArray = MedianFilter.median(InputImage);          //Removing Noise     
        new SelectorFrame().setVisible(true);
      
                                        
    }//GEN-LAST:event_jMenuItemSingleFrameActionPerformed
    
    public void displayImage(BufferedImage img)
    {
                                     
        DemoPanel pane = new DemoPanel(img);
        jPanel1=pane;
        setContentPane(new JScrollPane(jPanel1));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperResolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperResolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperResolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperResolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperResolution().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEnhance;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemContrast;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFCC;
    private javax.swing.JMenuItem jMenuItemMultiFrame;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSingleFrame;
    private javax.swing.JMenuItem jMenuItemZoomIn;
    private javax.swing.JMenuItem jMenuItemZoomOut;
    private javax.swing.JMenu jMenuType;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
